export const LOGIN_SUBMIT_BUTTON_CLICK = "LOGIN_SUBMIT_BUTTON_CLICKED";
export const SIGNUP_SUBMIT_BUTTON_CLICK = "SIGNUP_SUBMIT_BUTTON_CLICKED";
export const LOGOUT_BUTTON_CLICK = "LOGOUT_BUTTON_CLICK";